# Generated by Django 4.1.2 on 2022-12-16 13:26

from django.db import migrations
# создадим функцию, которая будет одним из аргументов,
# передающихся в обьект RunPython

def create_default_image

class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]
    # передадим объект(RunPython) который позворлит запускать код на python
    operations = [
        migrations.RunPython()
    ]
